.gitmodules
I guess `.gitmodules` got lost in the move. I discovered this after my CI build started to fail with:
```
Submodule path 'deps/libtock-c': checked out '668c80e3fe9c1623d8a9a5af422e8800f4e29b9b'
fatal: No url found for submodule path 'deps/libtock-c/lua53/lua' in .gitmodules
```
=> Add `.gitmodules` for Lua

examples/tests/mpu/Makefile, examples/tests/mpu/main.c
This pull request adds a simple test app to check that MPU regions are set up correctly. It consists of a number of different valid and invalid accesses to flash and RAM addresses, which should succeed or cause an MPU fault, respectively. Currently all of these are commented out, and the tester is able to uncomment the access they want to check. I'm not sure if this is an acceptable format for a test, so any feedback would be welcome.
=> Add MPU test

examples/ip_sense/README.md, examples/ip_sense/main.c, examples/tests/udp/udp_rx/Makefile, examples/tests/udp/udp_rx/README.md, examples/tests/udp/udp_rx/main.c, libtock/udp.c, libtock/udp.h
This commit is necessary to evaluate all of the work on the ip_userland branch for which a PR to the primary tock repo is forthcoming. 
1. Adds udp.c and udp.h, which interact with the userland driver in capsules/src/net/udp/driver.rs to enable tx/rx of udp packets from userland. 
2. updates to the ip_sense app to make it work with the 15.4 rx userland app and the aforementioned udp interface
3. the addition of a udp_rx userland test to test userland reception of UDP packets.
This commit has been tested by flashing two imixes with the ip_sense app and the 15.4 radio_rx app respectively and confirming that packets are correctly sent and acked. Additionally, a packet sniffer was used to confirm the packets being sent matched the expected packets. 
Documentation for how to use the ip_sense …
=> All userland changes from ip_userland branch in ptcrews/tock

libtock/crt0.c
We have to make sure there is enough accessible memory for the stack, bss, got and
data sections before trying to initialize them. Right now we're getting
away with it only because the kernel is liberal in letting us use memory
we haven't yet asked for.
=> Adjust stack and memory break before initializing

examples/tests/malloc_test01/Makefile, examples/tests/malloc_test01/README.md, examples/tests/malloc_test01/main.c
Runs malloc a few times, and it panics on the buggy version of crt0.
=> add malloc test app

libtock/crt0.c, userland_generic.ld
Before we assumed that got, data, and bss would be back-to-back-to-back.
However, with compiler aligned buffers that is no longer the case. This
updates the math so that we put the initial brk point in the correct
spot.
I believe this fixes the issue with the rot_* apps.
=> crt0: change data size calculation

userland_generic.ld
It's a simple change to the linker script that allows the GOT and DATA sections to be empty, and thus have equal start addresses as the bss section.
=> Allow got/data sections to be empty in linker script check

examples/tests/stack_size_test01/Makefile, examples/tests/stack_size_test01/README.md, examples/tests/stack_size_test01/main.c, examples/tests/stack_size_test02/Makefile, examples/tests/stack_size_test02/README.md, examples/tests/stack_size_test02/main.c, libtock/crt0.c
Before we moved the app break (with memop 0) and then moved the stack pointer. This however means we could be using a stack frame that is outside of the process's available memory. Because of MPU alignment issues this wasn't biting us, until I found an app that was using a much smaller stack (and therefore was moving the app break location much lower, causing the old stack pointer to be way far from the app's available memory).
This attempts to check for the condition where we are moving the brk location down, and moves the stack pointer before doing that.
I'm no assembly expert, so improvements in my assembly changes would be good.
Also I added two simple tests.
=> crt0: Move the stack pointer before shrinking brk

examples/ip_sense/main.c, examples/tests/udp/udp_rx/README.md, examples/tests/udp/udp_rx/main.c, examples/tests/udp/udp_send/Makefile, examples/tests/udp/udp_send/README.md, examples/tests/udp/udp_send/main.c
Updates some already existing UDP tests to be a bit cleaner. The IP sense app differs slightly from that requested in the tracking issue because we do not have rx support for IPv6 broadcast packets yet in the kernel.
=> Clean up UDP tests for 1.3 release testing

examples/lua-hello/Makefile
Adjusts the lua-hello app's Makefile to not request so much memory. Before this, the app requests just over 16kB, which gets rounded up to 32kB, which doesn't work with the amount of memory and alignment available on the NRF52.
Now works on NRF52
=> Lua app doesn't actually need as much memory

examples/tests/mpu_walk_region/main.c
The memory actually made accessible by the kernel has chenged, so the
mpu_walk_region test is no longer correct. The previous version assumed
memory was accessible all the way to the grant region, when now it is
only (guaranteed to be) accessible until the memory break returned from
`sbrk(0)`.
This change fixes the test.
=> Fix mpu_walk_region_test

.travis.yml, Configuration.mk
libtock-c's app makefile would try to detect whether elf2tab exists, and install it if not. It detected whether elf2tab exists by attempting to feed it a specific set of arguments and looking at whether it displayed output.
Prior to https://github.com/tock/elf2tab/commit/ecbb6039b79397b7c6cab606d34ed8c77faf7b50, elf2tab would spit out a help page with this set of arguments. However, a newer elf2tab will not output anything, causing the Makefile to try to install elf2tab.
This patch attempts to detect elf2tab using the `which` utility rather than calling elf2tab, which will hopefully be a more robust detection mechanism.
=> Correct elf2tab detection.

AppMakefile.mk, Configuration.mk, Helpers.mk, TockLibrary.mk
Before we assumed that `arm-none-eabi` would be able to compile code for all Tock architectures. With riscv that is no longer the case. This makes the toolchain a variable as well.
I definitely made this quickly and wanted to get it into its own branch because we need something like it to support riscv in the future.
I'm also realizing that `riscv64-unknown-elf` isn't going to be a simple swap in, at least because of PIC. So that is going to take some hacking, but I wanted to at least get a first draft of a mechanism to support different toolchains for different architectures in a pr.
=> make: support multiple toolchains

examples/tests/analog_comparator/main.c, examples/tests/gpio/main.c, examples/tests/tmp006/main.c
Calling yield() directly assuming a particular callback is bug-prone. If the runtime registers its own callbacks, then the application might assume a callback has occurred when it hasn't. This patch replaces all of the calls to yield() into calls to yield_for().
=> Remove use of yield() in test applications

examples/tests/ieee802154/radio_tx/main.c
Disambiguates failed transmissions from lack of acknowledgements.
=> Make the output of the 802.15.4 test app more useful.

libtock/crt0.c
We need to save app_start in a0 (first argument) before overwriting s0 in crt0. This allows app_start to be passed to _c_start instead of the frame pointer (which is the expected behavior).
=> Slight change to riscv crt0 assembly

AppMakefile.mk
Previously this was defaulting to just running the generic system `size`
command, which doesn't always know how to handle different architectures.
=> build: fix size prints to be arch-specific

.travis-install-gcc, .travis.yml, examples/ble-uart/main.c, examples/services/ble-env-sense/main.c, examples/witenergy/main.c
Just a maintenance update to stay current.
Motivated by my local machine updating and a slight change in warnings emitted.
=> Bump gcc version (to 2019q4)

examples/tests/udp/udp_virt_app_kernel/Makefile, examples/tests/udp/udp_virt_app_kernel/README.md, examples/tests/udp/udp_virt_app_kernel/main.c, examples/tests/udp/udp_virt_app_tests/app1/Makefile, examples/tests/udp/udp_virt_app_tests/app1/README.md, examples/tests/udp/udp_virt_app_tests/app1/main.c, examples/tests/udp/udp_virt_app_tests/app2/Makefile, examples/tests/udp/udp_virt_app_tests/app2/README.md, examples/tests/udp/udp_virt_app_tests/app2/main.c, examples/tests/udp/udp_virt_rx_tests/app1/Makefile, examples/tests/udp/udp_virt_rx_tests/app1/README.md, examples/tests/udp/udp_virt_rx_tests/app1/main.c, examples/tests/udp/udp_virt_rx_tests/app2/Makefile, examples/tests/udp/udp_virt_rx_tests/app2/README.md, examples/tests/udp/udp_virt_rx_tests/app2/main.c, libtock/ieee802154.c
This PR introduces a number of UDP tests that allow for comprehensive testing of simultaneous UDP sending and reception between:
- multiple apps
- apps and capsules
- multiple capsules
These tests are described in detail in their READMEs and in the corresponding kernel tests in `boards/imix/src/udp_lowpan_test.rs` in the main Tock kernel. Currently, all of these tests have only been tested on Imix. 
Additionally, this PR includes a small fix for the ieee802154 interface to ensure that the radio is always actually ready when ieee802154_up() returns (on Imix there appears to be a small delay between when that bit is set and when the radio is actually ready).
=> Udp virtualization tests

userland_generic.ld
If an ELF has a .sdata section it won't be copied to the TBF file. To
ensure that it makes it in let's include it in the data section.
=> userland_generic.ld: Include .sdata in the data section

AppMakefile.mk, Configuration.mk
I found some places in the Makefiles that hadn't been updated for RISC-V in particular those that pertain to generating debug binaries.
=> fix debug flags for riscv

examples/ble_passive_scanning/advertisement.cpp, examples/ble_passive_scanning/advertisement.h, examples/ble_passive_scanning/main.cpp
* Only read the first 4 bits instead of the first byte to get the PDU type.
* Read out TxAdd and RxAdd bytes correctly.
* Some improvements on printouts and some additional constants.
=> Fix wrong header handling in ble passive scanning example

examples/tests/gpio/main.c
This makes test mode 0 work in the gpio test app.
=> gpio test: actually set condition variable

examples/tests/imix/main.c
Currently, the Imix test app will print `Error sending packet -13` if a receiving device is not also active nearby and acking packets sent by the sender. This is a result of the 15.4 stack now correctly returning ENOACK when packets are transmitted successfully but not Acked (https://github.com/tock/tock/pull/758). 
This PR fixes the Imix app to not indicate an error if TOCK_ENOACK is returned when sending a 15.4 packet.
It also removes the "kernel" comment to reflect that LED(0) is no longer the led labeled "kernel" as that LED is no longer accessible from userspace.
=> Imix app: dont print error for enoack

libtock/crt0.c, userland_generic.ld
The motivation for this change is to make sure that applications are
compiled with the GOT, data, and BSS sections at the relative offset in
memory that they will be when an app actually executes. Currently, these
sections are at an offset from the start of memory, when they are
actually used after the stack (and the stack is at the start of memory).
This works fine for PIC apps, since the GOT, data, and BSS sections can
be relocated both to where the app is in flash/memory, and to move them
past the stack. But, for apps compiled for fixed addresses, the GOT,
data, and BSS addresses cannot be arbitrarily moved, they must end up in
memory at the addresses the compiler expects them to be.
The key fix here is to add a `.stack` section to the linker file, so
that the GOT, data, and BSS …
=> crt0 and .ld: Cleanup & add stack as section

userland_generic.ld
This generates a symbol that elf2tab uses to check for fixed addresses.
=> Mark ORIGIN(SRAM) in the linker script

libtock/screen.c
This fixes a bug in the screen library, the screen_set_frame was not yielding and the applications would fault.
=> screen_set_frame should yield

AppMakefile.mk
As part of https://github.com/google/tock-on-titan we're trying to all build output written to a location outside of the source directory. For libtock-c we're explicitly setting individual instances of $(LIBNAME)\_BUILDDIR (e.g. libtock_BUILDDIR) externally. This works, except that LIBS_$(arch) ends up with an incorrect reference as this is currently hard-coded.
This change updates the EXTERN_LIB_RULES macro to generate LIBS_$(arch) with $(LIBNAME)_BUILDDIR if set externally and otherwise defaults to the hard-coded path.
=> Use $(LIBNAME)_BUILDDIR for referencing library binary

Configuration.mk
Change the addresses for the second riscv app for the arty board.
Since I originally chose those addresses I've learned:
- The erase size appears to be 0x10000. So, making apps at least 0x10000 makes tockloader work better, but the second app must be at address offset 0x40000.
- The .data section is huge with my riscv compiler. To compensate, give the first app more memory.
=> make: update arty-e21 addresses

libtock/crt0.c
I'm finding that for certain RISC-V apps the compiler is still generating a GOT, even though the addresses are fixed. This just adds support to crt0 so that even in the no-pic case the got gets copied if there is one.
=> crt0: no PIC still has a GOT sometimes

userland_generic.ld
The RISC-V compiler likes to emit more sections, and if we don't include them in .text and .bss then they get created as their own ELF sections and elf2tab doesn't handle that well.
=> ld: add extra riscv sections

examples/tests/udp/udp_virt_app_tests/app2/main.c
These tests worked originally, but depended on one app executing certain lines of code first, for the portion where both apps attempt to bind to the same port. I used a 10ms delay to achieve this. However, because the time to send a multi-fragment UDP packet is longer than 10ms, this test only worked originally because app1 happened to always be scheduled first on the old priority scheduler. For a 10ms delay to be enough, it must be placed before the packet is sent, ensuring that app1 sends its packet first.
Kinda a confusing explanation, but basically this test assumed an order of execution which was not exposed until we switched to a round robin scheduler on Imix. This PR fixes it.
=> fix race condition in UDP virtualization tests

shell.nix
With the `Cargo.lock` file of elf2tab updated in https://github.com/tock/elf2tab/pull/26, bump the `elf2tab`-version which is built as part of the `nix-shell` derivation to the current version.
This is also required to support the `--protected-region-size` argument, which is required to build for RISC-V targets (as they require knowing the flash address in advance). This issue was also noted in #117.
=> nix elf2tab: bump version to 0.6.1

examples/tests/hail/main.c, examples/tests/imix/main.c
The ADC always returns samples as 16 bits, even though the ADC may use
fewer bits. This fixes the calculation since the 12 bits of SAM4L adc
will always be the upper 12 bits.
=> hail app: adc samples in upper bits

examples/adc/Makefile, examples/adc/README.md, examples/adc/main.c
This PR adds an ADC example app that can be used out of the box with the STM32F412G Discovery and BBC micro:bit v2.
=> ADC Example App

examples/tests/udp/udp_rx/main.c, libtock/udp.c
Updates the UDP driver to use the 2.0 system calls. Mostly works, but matching on error codes does not seem to work, I think this will need to be updated once the new error types are inserted in libtock-c
=> UDP driver to 2.0 syscalls

libtock/console.c, libtock/spi.c
@hudson-ayers Caught a bunch of places where code incorrectly grabbed the second value (data[1]) instead of the first (data[0]) for the error code of a 2.0 command invocation. This fixes them.
=> Fix erroneous use of syscall_return_t.data[1] for fetching error code (should be data[0])

libtock/analog_comparator.c
Ports the analog comparator to use tock 2.0 syscalls.
Tested on Imix (though only in the polling mode, I don't actually have any wires available to test the interrupt mode).
=> analog comparator to tock 2.0 syscalls

examples/tests/callback_remove_test01/main.c, libtock/alarm.h, libtock/alarm_timer.c, libtock/internal/alarm.h, libtock/internal/alarm_internal.c, libtock/led.c, libtock/rng.c
This PR makes three changes:
- It updates the alarm/timer library to use the 2.0 system calls and their return values
- It updates the alarm/timer library to use the system call that passes a reference and a dt, rather than an absolute time for an alarm; this prevents bugs where the absolute time has fallen behind now and the kernel interprets this as an alarm in the far far future
- It also (trivially) updates the LED library routines to use the new system calls. This is important for led_count(), which the alarm test applications depend on; without this fix they crash by malloc'ing too many alarms.
=> Updates alarm to use 2.0 system calls.

libtock/adc.c
The pull request updates the ADC driver to use the Tock 2.0 API (tock/tock#2312)
=>  Tock 2.0: update ADC driver to use 2.0 API

examples/tests/dac/main.c, libtock/dac.c, libtock/dac.h
This pull request ports the DAC driver to the new Tock 2.0 system call interface. Tested using the `dac` test on Hail with the related changes in to the Tock kernel: tock/tock#2285.
=> Port DAC library to Tock 2.0 system call interface

libtock/gpio_async.c
Ports gpio-async to tock 2.0 syscalls.
This is untested, as I do not have any Tock hardware that uses the async gpio interface.
=> Gpio async to tock 2.0 syscalls

examples/tests/ieee802154/radio_rx/main.c, libtock/ieee802154.c, libtock/ieee802154.h
This has been tested using the radio_rx and radio_tx example apps, which successfully exchange frames between an imix and an nrf52840dk.
One notable change as part of this is the need to explicitly unallow the receive buffer before accessing it again -- a task which previously was left up to the kernel capsule.
=> Update Ieee802154 driver to Tock 2.0 syscalls

examples/courses/2018-11-SenSys/sensys_udp_rx/main.c, libtock/crt0.c, libtock/tock.c, libtock/tock.h
This PR contains a few small cleanups to:
- Add some missing includes and remove ones that aren't required
- Rename `asm` to `__asm__` to be more flexible with `-ansi` and `-std` arguments (see https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Extended-Asm.html)
=> A handlful of fixes and cleanups

libtock/tock.h
This updates libtock-c's values for ErrorCodes from the kernel to agree with https://github.com/tock/tock/pull/2412 .
=> Update ErrorCodes to agree with #2412 from tock.

libtock/ble.c, libtock/ble.h, shell.nix
This pull request makes minimal changes to update the libtock Bluetooth Low Energy driver to the Tock 2.0 interface as implemented in tock/tock#2411
I successfully tested both advertising and scanning on an Arduino Nano BLE 33 sense with the `ble_advertising` and `ble_scanning` apps.
Piggybacking on this is a small change to the Nix shell expression to use tockloader 1.6.0, which supports programming the Arduino Nano.
=> Update BLE advertising and scanning for the Tock 2.0 interface

libtock/ipc.c, libtock/ipc.h
The only change in the IPC interface is the return type of `ipc_share`,
which is now an `allow_return_t` instead of an int. The implementation
of `ipc_discover` now performs a command in addition to the
allow_readonly to perform the discover and an additional allow to get
ownership of the buffer back.
=> Port IPC to 2.0 driver

libtock/lsm303dlhc.c
This PR ports the lsm303dlhc to tock 2.0. all command calls return success() and were grouped into helper functions already, so this was quite straightforward.
=> Port Lsm303dlhc to Tock 2.0

libtock/humidity.c, libtock/humidity.h, libtock/temperature.c, libtock/temperature.h
In porting over the capsules, somehow the libtock-c parts were missed for temperature and humidity. This updates them to the 2.0 syscall API. Part of #177
=> Update temperature and humidity to use 2.0 API

examples/tests/imix/main.c, examples/tests/udp/udp_send/main.c
Running the Imix app against master in the kernel is currently broken since we removed the 15.4 driver from the Imix platform. This updates the Imix app to no longer use the 15.4 driver, and updates the udp app to not use the 15.4 driver to configure the PAN, as this is done in main.rs now anyway.
This app also changes the code for reading from the accelerometer to not depend on the synchronous call succeeding. Many of the recently produced Imixes do not have the ninedof chip, so this app hangs when used on those boards, because a callback is never generated. This fixes that issue via somewhat of a hack.
A change still needs to be made to udp_rx to account for the fact that it is no longer possible to set the MAC address from userspace using the 15.4 driver, but that will need probably …
=> update imix app to reflect sometimes absent ninedof + move to UDP

libtock/crt0.c
The GCC documentation states:
"When writing code that can be compiled with -ansi and the various
-std options, use __asm__ instead of asm"
Switch to use __asm__ to be more flexible.
=> libtock: Use __asm__ instead of asm

libtock/tock.c
On RISC-V 32bit platforms, the system call class identifier for yield (0) must be passed in the 5th argument register, that is a4 or x14 respectively. Passing it in the 6th argument register (a5) causes undefined behavior.
This bug was hard to trace down, because the system call tracing output was misleading, putting the blame on other parts of the
codebase. The LiteX simualtor (Verilator) RISC-V formal interface, together with the Ibex instruction traces helped to hunt this one down.
Fixes: 7d91971d303564 ("RISC-V support for yield-no-wait.")
Signed-off-by: Leon Schuermann <leon@is.currently.online>
Tagging as Tock 2.0 since this was introduced as part of the transition.
=> rv32i: fix yield system call class argument register

examples/sensors/main.c
Avoid unbounded stack growth in case sensor readings take too long by
using multiple `timer_in` instead of `timer_every`.
Also, print proximity sensor reading even when 0.
=> More robust sensors app

Configuration.mk
The kernel now starts process memory at 0x80002800 not 0x80002400 for the hifive1b board.
=> riscv: update to new hifive1b ram address

AppMakefile.mk
I'm not sure why this was there, but the make system seems to work fine without it. I tried changing the targets, deleting the custom.ld file, doing make clean, everything worked like normal.
The real benefit is that tockloader no longer warns that you should run `make`.
=> make: do not rebuild ld file each time

libtock/tock.c
Currently it only accepts success with no args. This breaks for a driver like ADC.
=> driver_exists function needs to accept any success case

libtock/i2c_master_slave.c, libtock/i2c_master_slave.h
This requires https://github.com/tock/tock/pull/2619
=> libtock/i2c_master_slave: Add ReadOnly buffer support

libtock/i2c_master.c
TOCK_I2C_MASTER_CB should be 0 not 1 according to https://github.com/tock/tock/blob/9f159e0c06e27b2357e3b20be6c90b3396bbd7b9/capsules/src/i2c_master.rs#L200 . I have also confirmed that it only works with this change.
=> Fix i2c_master

libtock/screen.c, libtock/text_screen.c
With new allow_readonly syscall, interfaces should reflect immutable buffer.
This might make #217 happy, but I doubt it. The interface actually _does_ pass uninitialized memory to the initial allow, which is fine, as we haven't asked the screen to draw the buffer yet. Still, the little const qualifiers should definitely be added; the initialization is separate concern.
=> add missing const qualifiers

Configuration.mk
This PR adds 
- the command line for elf2tab to add the `KernelVersion` header
- the automatic updatce of elf2tab.
This is needed to add the `KernelVersion` header (https://github.com/tock/tock/pull/2669)
=> Added kernel version and automatic update for elf2tab

examples/tests/mpu_heap_end/main.c, libtock/sys.c, libtock/tock.c, libtock/tock.h
This updates the memop syscall to use the same `memop_return_t` format as the other syscalls. This allows callers of memop to differentiate errors from success.
=> memop: use memop_return_t

libtock/screen.c, libtock/text_screen.c
The pull request updates the `screen` and `text_screen` drivers to allocate clean buffer, fixing #217 in a nice way.
=> Update screen to allocate clean buffer

examples/tests/udp/udp_rx/README.md, examples/tests/udp/udp_rx/main.c, libtock/ieee802154.c, libtock/ieee802154.h
This ensures that the udp_rx test does not attempt to block on the 15.4 driver since that driver is no longer present on Imix due to code size limitations.
=> fix udp tests that relied on 15.4 driver being present

examples/build_all.sh, examples/courses/2018-11-SenSys/important-client/app1/main.c, examples/courses/2018-11-SenSys/important-client/app2/main.c, examples/tests/udp/udp_virt_app_kernel/main.c, examples/tests/udp/udp_virt_app_tests/app1/main.c, examples/tests/udp/udp_virt_app_tests/app2/main.c, examples/tests/udp/udp_virt_rx_tests/app1/main.c, examples/tests/udp/udp_virt_rx_tests/app2/main.c, libtock/udp.c
The build_all script (which is run by CI) only searched 4 directories deep so some apps were not being built. This PR modifies that to 6 directories deep and fixes breakages which had gone uncaught. Depends on https://github.com/tock/libtock-c/pull/235
=> Build all apps

examples/tests/udp/udp_virt_app_kernel/main.c, examples/tests/udp/udp_virt_app_tests/app1/main.c, examples/tests/udp/udp_virt_app_tests/app2/main.c, examples/tests/udp/udp_virt_rx_tests/app1/main.c, examples/tests/udp/udp_virt_rx_tests/app2/main.c, libtock/udp.c
Remove use of 15.4 driver, and correct some compilation errors from function signatures changing.
=> fix bugs in tock 2.0 port for UDP virtualization test apps

Configuration.mk
Since we are now adding more TLVs we need to allocate more space before the start of the actual binary for hifive1b.
=> make: more space for hifive1b header

Configuration.mk
This wastes less space compared to what is currently supported.
=> Configuration.mk: Update addresses for the ESP32-C3

examples/ble-uart/Makefile
Not sure why this was added in 156b67b2ae6925478e7e9d6ff69c7729ecd6817b
=> ble-uart app does not need that much memory

libtock/tock.c
The a4 register was being clobbered but it wasn't marked as so. This bug was exposed when compiling apps with Clang.
=> libtock: fix clobbering of RISC-V a4 register in syscalls

userland_generic.ld
448 * 1024 = 0x70000
This fixes the issue in #250.
=> linker file: make length match comment

libtock/crt0.c
We have logic for the kernel to try to track the lowest the stack ever gets for a process (at least the lowest whenever it calls a syscall). I've noticed for a while that it is always the same as the entire stack size.
I traced it back to crt0, where because we call memop(10) to tell the kernel we moved the stack pointer, _then_ call memop(11) about the heap, and only _then_ actually move the stack pointer, the first memop causes the debug tracking to reset, and then the second memop causes the kernel to set the lowest stack to the very bottom (since the stack only fits one svc frame). It is then effectively useless at that point.
This sets the sp earlier in crt0, so that memops after the memory is allocated use the new stack and the accounting works as expected.
=> crt0: set sp earlier so sp debug works

Configuration.mk
When running multiple apps on OpenTitan we need to build apps at a few
different addresses. This commit sets up the build system to build the
OpenTitan apps at all of the addresses required to run the automated app
tests included in the Tock kernel.
This greatly simplifies testing apps on OpenTitan.
The overhead of building an app for multiple different addresses is low,
so this doesn't extend the build time by very much.
While we are at it let's also split out the current Arty build addresses
to make things clear.
This PR also adds support for the Arch toolchain name.
=> Configuration.mk: Build system improvements

libtock/read_only_state.c, libtock/read_only_state.h, libtock/tock.c, libtock/tock.h
This is a companion PR with the Tock PR here: https://github.com/tock/tock/pull/2381
This adds support for getting information from the Tock kernel using read only state.
This also includes adding support for a `quick_yield()` that doesn't require a syscall if there are no pending tasks.
=> libtock: Support for userspace read allow and read only state

libtock/tock.c
When reviewing #170, I noticed that there's a mix of `1` and `-1`
used to express the same error (I think)?
Looks like this came as part of the big batch change in 77e90c1f.
@phil-levis Did you have a reason for some of these being `1` and some `-1`?
=> libtock: Consistent error code for Invalid exit

.gitmodules
Today, Github deprecated unauthenticated git protocol access (https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git) which broke our checkout action because we used it for the lua submodule. This PR should fix it.
=> fix checkout action

README.md
Fixes up a typo I made here, where `make linux` builds the linux glibc-based
toolchain instead of newlib (with just `make`).
Tested, by building libtock-c apps with `make RISCV=1` - compilation OK
edit: added `make linux` with a note as some tock makefiles use
`riscv64-linux-gnu-objcopy`
Signed-off-by: Wilfred Mallawa <thulith.mallawa@uqconnect.edu.au>
=> README: fixup typo with build instructions

examples/tests/nonvolatile_storage/main.c
The nonvolatile storage test app only tests the first 512 byte region of the configured flash storage. It should also test the end of the configured flash storage to ensure it is configured properly. These changes were used to validate tock/tock#3099
- Add test for writing 512 bytes at the end of the configured memory region.
- Add test for writing 512 bytes beyond the end of the configured memory region, is expected to fail.
=> Nonvolatile storage tests for end of flash region

examples/tests/analog_comparator/main.c
These callback arguments were incorrectly marked as unused.
=> analog_comparator: dont marked used callback arguments as unused

Configuration.mk
This is in response to issue tock/libtock-c#282, which exposed that `rv32i` support is not prevalent among prebuilt RISC-V embedded toolchains. Users of such toolchains are faced with linker errors when trying to build a `rv32i` target, which is included by default in all RISC-V builds. As of tock/tock#2860 the `litex_sim` board is actually using a VexRiscv CPU with multiplication and compressed instruction support and hence this target definition can be changed to target `-march=rv32imc` instead. Yet, it does not solve the underlying toolchain issue. Refer to [1] for more information.
Signed-off-by: Leon Schuermann <leon@is.currently.online>
[1]: https://github.com/tock/libtock-c/issues/282
Closes #282.
=> Configuration.mk: change litex_sim target definition to rv32imc

README.md
This fixes some formatting issues, and removes the note about brew on mac compiling the riscv compiler as the multilib version is now standard.
=> readme: July 2022 update and formatting

libtock/tock.h
Matches updates in https://github.com/tock/tock/pull/3175
=> fix SuccessU32U64 syscall return variant name to match TRD104

AppMakefile.mk, Configuration.mk, Helpers.mk, Program.mk, TockLibrary.mk
I added comments to better document the libtock-c makefiles.
I also reorganized the `Configuration.mk` file which has grown over time and gotten a little confusing. Now the variables are set in three groups: shared flags, RISC-V flags, and Cortex-M flags. This makes for a complex diff, but it is mostly just moving lines to create these groups.
=> Update and Refresh libtock-c Makefiles

AppMakefile.mk, Configuration.mk, examples/lua-hello/Makefile
before:
```
$ make RISCV=1
Application size report for target cortex-m0:
text	   data	    bss	    dec	    hex	filename
1664	    196	   2400	   4260	   10a4	build/cortex-m0/cortex-m0.elf
Application size report for target cortex-m3:
text	   data	    bss	    dec	    hex	filename
1456	    196	   2400	   4052	    fd4	build/cortex-m3/cortex-m3.elf
Application size report for target cortex-m4:
text	   data	    bss	    dec	    hex	filename
1456	    196	   2400	   4052	    fd4	build/cortex-m4/cortex-m4.elf
Application size report for target cortex-m7:
text	   data	    bss	    dec	    hex	filename
1456	    196	   2400	   4052	    fd4	build/cortex-m7/cortex-m7.elf
Application size report for target rv32imac.0x20040060.0x80002800:
text	   data	    bss	    dec	    hex	filename
1704	    108	   2404 …
```
=> Change `make size` to display family size information, rather than individual size listings

Configuration.mk, examples/lua-hello/Makefile
This automatically generates `TOCK_ARCH_FAMILIES` from the `TOCK_TARGETS`. It allows users to only specify the list of target binaries generated, including fixed flash and RAM addresses for RISC-V targets. The Makefile infrastructure will automatically determine which toolchain steps to use throughout the build process (e.g. in the size calculation phase).
=> Configuration.mk: automatically generate TOCK_ARCH_FAMILIES

AppMakefile.mk, Helpers.mk
Output now looks like:
```
$ make
CC        main.c
LD        build/cortex-m0/cortex-m0.elf
CC        main.c
LD        build/cortex-m3/cortex-m3.elf
CC        main.c
LD        build/cortex-m4/cortex-m4.elf
CC        main.c
LD        build/cortex-m7/cortex-m7.elf
E2T        build/blink.tab
Application size report for arch family cortex-m:
text	   data	    bss	    dec	    hex	filename
1664	    196	   2400	   4260	   10a4	build/cortex-m0/cortex-m0.elf
1456	    196	   2400	   4052	    fd4	build/cortex-m3/cortex-m3.elf
1456	    196	   2400	   4052	    fd4	build/cortex-m4/cortex-m4.elf
1456	    196	   2400	   4052	    fd4	build/cortex-m7/cortex-m7.elf
6032	    784	   9600	  16416	   4020	(TOTALS)
```
Not clear why we weren't showing that step before.
=> make: add trace for elf2tab

libtock/i2c_master.c, libtock/i2c_master.h
To match https://github.com/tock/tock/blob/master/capsules/src/i2c_master.rs#L130
Fixes #260.
=> i2c_master: fix len in syscalls

userland_generic.ld
This pull request makes the ARM.exidx section *NOLOAD*. 
It seems that starting with version 0.10.0, `elf2tab` has a different way of setting up the TBF file from the ELF sections. Before this version, the ARM sections, like `.ARM.exidx` where ignored. They seem to be added now exactly where the relocation section should be. This make apps that include this section to fault. Not all apps have include this section, for instance a simple *hello* does not.
This is how the sections look like:
```
Min RAM size from segments in ELF: 13012 bytes
Number of writeable flash regions: 0
Kernel version: 2.0
Adding segment. Offset: 72 (0x48). Length: 162972 (0x27c9c) bytes.
Contains section .crt0_header. Offset: 72 (0x48). Length: 40 (0x28) bytes.
Contains section .text. Offset: 112 (0x70). Length: …
```
=> Make .ARM.exidx NOLOAD

libtock/lora_phy.c, libtock/lora_phy.h
This adds userspace support for the new Tock [LoRaMac capsule](https://github.com/tock/tock/pull/3360)
=> lora: Add support for a LoRa capsule

libtock/alarm.h
As far as I can tell the `alarm_read()` function does not exist.
=> remove alarm_read() from alarm.h

libtock/console.h
There is no implementation of putstr() so let's remove the header definition.
=> libtock: console: Remove putstr definition

examples/tests/keyboard_hid/main.c, libtock/usb_keyboard_hid.c, libtock/usb_keyboard_hid.h
Cleans up the USB Keyboard HID driver by no longer requiring an input buffer for sending strings or characters. Instead, make a local buffer on the stack and use that. The synchronous function that actually sends a buffer has not been changed.
When testing, I found that `usb_keyboard_hid_send()` would sometimes return `ERESERVE` . This behavior occurs in the original version as well before this commit. `ERESERVE` means either the buffer couldn't be taken, or something else couldn't unwrap (I can't follow that mess). https://github.com/tock/tock/blob/master/capsules/extra/src/usb_hid_driver.rs#L205-L231 However, HID output does appear correctly and the app keeps working, so I guess we can keep ignoring it for now...?
=> Remove unnecessary input buffer

.github/workflows/ci.yml, README.md
Analog to https://github.com/tock/tock/pull/3621. Given that `www.cs.virginia.edu` seems to work now, we should use that and point people to that URL.
=> README/CI: fix pre-compiled RISC-V toolchain URL and add mirror

libtock/unit_test.c
Ensure the service has time to register.
With KV testing I've had to manually add this delay to get the unit test framework to work.
=> unit test: delay before discover

examples/tutorials/hotp/hotp_oracle_complete/Makefile, examples/tutorials/hotp/hotp_oracle_complete/main.c
This changes the HOTP app to use KV rather than app state.
Advantages of KV:
1. Doesn't change the binary, so if we add credentials they remain valid.
2. Can be supported in libtock-rs.
This also just prints the code if usb-hid isn't set up.
I tested this with an nrf52840dk board and it seemed to work as expected. The programmed keys continued to work after resets.
=> Update the HOTP App to use Key Value Store

libtock/alarm.h, libtock/alarm_timer.c
Implement the _gettimeofday() function, which fixes build issues with C code that uses the gettimeofday syscall.
=> libtock: sys: Implement _gettimeofday

examples/tests/adc/main.c, examples/tests/adc_continuous/main.c, examples/tests/adc_single_samples/main.c, examples/tests/udp/udp_rx/main.c, libtock/adc.c, libtock/adc.h, libtock/analog_comparator.c, libtock/gpio.c, libtock/gpio.h, libtock/ieee802154.c, libtock/ieee802154.h, libtock/read_only_state.c, libtock/read_only_state.h
Bring libtock-c into consistency with the changes in [this PR](https://github.com/tock/tock/pull/3613/).
=> libtock: update breaking driver existence check changes

examples/i2c-usb-bridge/Makefile, examples/i2c-usb-bridge/README.md, examples/i2c-usb-bridge/main.c
This application bridges data to and from the serial console to the I2C bus.
This allows a PC to communicate with an I2C device via a USB port.
On a PC you can connect to the UART of the device running this application to access the I2C bus. The Tock device will then act as a I2C master to interact with I2C devices.
=> example: i2c-usb-bridge: Initial support

shell.nix
With #353 in, we can finally get rid of the custom Toolchain build for Nix-based build environments. While we're at it, we also remove a package dependency on J-Link that has been removed upstream for security concerns (though will be re-added soon), and bump Tockloader to a proper v1.11.0 release.
=> Remove custom RISC-V toolchain from Nix shell, remove Segger J-Link, update Tockloader to v1.11.0

.github/workflows/ci.yml, AppMakefile.mk, Configuration.mk, Precompiled.mk, lib/fetch-libc++.sh, lib/fetch-newlib.sh
This ensures that prior to building a C++ source file, both libc++ and newlib are available. It fixes a race condition in the GitHub actions CI which would fail by first building `examples/cxx_hello/main.cc`, which proceeded to build it with neither newlib or libc++ fetched. We make C++ objects depend on newlib as well, as they can feature includes from the C standard library.
This also sneaks in a commit that kicks of GH actions builds on each push, matching the comment in that workflow definition. This mirrors the CI setup from the Tock repo. Happy to split this into a separate PR.
=> AppMakefile: depend on libc++ and newlib for cc,cpp,cxx build rules

libtock/alarm_timer.c
While working on the OpenThread libtock-c port, @atar13 and @Samir-Rashid  observed a bug on the nrf52840dk board attempting to use the `gettimeasticks` functionality. When tested with the following code:
```c
// code below abbreviated for demonstration
for (int i = 0; i < NUM_SAMPLES; i++) {
uint32_t cur_time_ms = gettimeasticks(&tv, NULL);
clock_return[i] = cur_time_ms;
delay_ms(1);
}
// print results
for (int i = 0; i < NUM_SAMPLES; i++) {
uint32_t item = clock_return[i];
printf("item %d:\t %lu\n", i, item);  // output wraps around at about 128
}
```
they observed that the the time in milliseconds wrapped around to zero approximately every 128 ms (see below)
```
item 26:         103
item 27:         107
item 28:         111
item 29:         115
item 30:         119
item 31:         123 …
```
=> Alarm overflow - gettimeasticks

libc++/docker/docker-libc++-10.5.0/Dockerfile, libc++/docker/docker-libc++-12.3.0/Dockerfile, libc++/docker/docker-libc++-13.2.0/Dockerfile, newlib/docker/docker-newlib-4.2.0.20211231/Dockerfile, newlib/docker/docker-newlib-4.3.0.20230120/Dockerfile
This makes the commit hash used to build newlib and libcpp new enough to include the full PR on libtock-c/master.
The commit is the merge commit for #353.
Otherwise the commit is just somewhere in the middle of the PR. But I couldn't include this in the PR until the merge commit was created.
=> newlib/libcpp: update commit hash in dockerfile

TockLibrary.mk
Our build all file adds the `-Werror` CFLAG, which in general is good, but when compiling a library we don't necessarily have control over the library not having any warnings. This makes CI fail when using external libraries.
But, we want to enforce no warnings on libtock. Hmm...
=> make: tocklibrary: never build with -Werror

lib/fetch-libc++.sh, lib/fetch-newlib.sh
This resolves #373 and was tested by successfully fetching these files and building an example application. 
In addition to resolving this bug, the `-q` flag was removed from the `wget` command to make debugging future connectivity issues easier and to display a download progress bar.
=> Resolve fetching sha256sum failure

examples/tests/ieee802154/radio_rx/main.c, examples/tests/ieee802154/radio_rxtx/main.c, libtock/ieee802154.c, libtock/ieee802154.h
This PR updates the libtock-c 15.4 functions to use the receive ring buffer the kernel now expects. I updated the relevant 15.4 libtock functions in addition to the various test apps. Additionally, I attempted to update logic using hard coded values for the frame meta data length.
The test apps are currently operating as expected with these changes.
=> IEEE 802.15.4 Updates for Kernel Ring Buffer

README.md
=> readme: no RISCV flag

TockLibrary.mk
This is supposed to match the actual makefile line.
=> make: tocklib: fix debug comment

u8g2/Makefile
Building libraries in the context of other compilations seems to need the directory for all source files.
=> u8g2: use paths in src file

TockLibrary.mk
This fixes an issue when multiple Tock libraries are used in the same build. With `?=`, the value is "reset" for each instantiation of TockLibrary, causing the build directory for all libraries to be set to whichever library is included last. With `:=` this does not occur.
=> make: TockLibrary: unconditionally set build dir

AppMakefile.mk, Program.mk
Tockloader has advanced a lot. No need to specify the board. `make install/flash/program` should all work.
=> make: install: update to modern use of tockloader

TockLibrary.mk, libtock/Makefile, lua53/Makefile, lvgl/Makefile, simple-ble/Makefile, u8g2/Makefile
This changes TockLibrary to not use a flat file structure when compiling libraries, but to use the directory hierarchy when generating the build rules. This way if a library has multiple files with the same name, or multiple libraries have files with the same filename, if the file in the _second_ library changes, the library gets rebuilt.
I tested this on the libtock rewrite branch, and if I change something in libtock-sync with this change and rebuild an app the sync library rebuilds.
The important step here is that `$($(LIBNAME)_SRCS)` must be set by the library to the longest shared prefix of all the source files. This is important for decoupling the source files from the folder which represents the library. It also allows multiple libraries (with perhaps different flags) to be …
=> make: TockLibrary: Build in full paths

AppMakefile.mk, doc/compilation.md, u8g2/Makefile, u8g2/Makefile.app, u8g2/Makefile.setup
This adds a `Makefile.setup`, which, if provided, is used by `AppMakefile` to fetch and then build the library for an app that requires it.
The key is this in `AppMakefile`:
```make
#
#
define EXTERN_LIB_BUILD_RULE
ifneq "$$(wildcard $(2)/Makefile.setup)" ""
$(1):
$$(MAKE) -C $(2) -f Makefile.setup all
$$(MAKE) -C $(2) -f Makefile all
else
$(1):
$$(MAKE) -C $(2) -f Makefile all
endif
endef
```
which runs `make Makefile.setup` and then `make` in the library directory if the build directory does not exist. The setup script downloads the library source. The regular makefile builds it. These are split because the regular build makefile needs all of the source files to be present to create the build rules.
=> make: support automatically building libraries when compiling apps

TockLibrary.mk, libtock/Makefile, lua53/Makefile, lvgl/Makefile, simple-ble/Makefile, u8g2/Makefile
The intent of `$($(LIBNAME)_SRC_ROOT)` was to have a path prefix that was unique for each library, so even different libraries with the same file names would compile as expected. This approach worked fine for libraries like openthread and u8g2, but for libtock and libtock-sync it does not. Those libraries have the same paths and the same files.
In hindsight, it's probably better to just use the libtock-c folder as the root, and base everything off of that. Therefore every file has a unique path.
This effectively reverts adding `$($(LIBNAME)_SRC_ROOT)` and instead just uses `$(TOCK_USERLAND_BASE_DIR)` in its place. Crucially, this allows libtock and libtock-sync to compile side-by-side.
=> make: use `$(TOCK_USERLAND_BASE_DIR)` as ROOT

shell.nix
Updates the pinned Tockloader revision in libtock-c to v1.12.0, including fixes for the nRF52840 accessible flash range.
Tested by entering nix-shell.
=> Update pinned Tockloader rev to v1.12.0

libtock/services/alarm.c
The prior implementation faced a trade off of imprecise time conversion or overflowing values. To prevent overflowing values, microseconds were calculated as `tv->tv_usec = (remainder * 1000) / (frequency / 1000);`. Scaling $\frac{frequency}{ 1000}$ losses the frequency's precision and introduces error in the conversion. 
In trying to fix this, I attempted to first convert to milliseconds, followed by an additional remainder calculation (using uint32). However, this also faced an issue of the intermediate calculation overflowing for frequencies greater than 4MHz. 
This updates `gettimeasticks` to use a uint64_t for calculations to avoid overflows and minimize loss of precision. If there are strong objections to introducing a uint64 here, we can also only perform the uint64 operation for …
=> Resolve gettimeasticks imprecision

libtock-sync/display/screen.c, libtock-sync/display/text_screen.c, libtock-sync/interface/usb_keyboard_hid.c, libtock-sync/peripherals/usb.c, libtock-sync/storage/nonvolatile_storage.c, libtock-sync/storage/sdcard.c
These were missed in the original PR, and it seems that newer compilers don't care but older versions (circa 2020) do.
=> libtock-sync: add missing static

libopenthread/platform/radio.c
This PR updates the radio PAL transmit logic to correctly handle cases of radio transmission failure or attempting to send on unsupported channels. Additionally, because Tock abstracts the radio, the "radio" exposed to userland is capable of transitioning from sleep to tx for all intensive purposes.
=> LibOpenThread Radio Minor Changes

examples/openthread/openthread_hello/main.c, examples/openthread/openthread_udp_rx/main.c, examples/openthread/openthread_udp_tx/main.c, examples/tests/openthread/openthread_timer_test/main.c, examples/tutorials/thread_network/06_openthread/main.c, examples/tutorials/thread_network/07_openthread_final/main.c, examples/tutorials/thread_network/screen/openthread_app/main.c, libopenthread/platform/Makefile.app
That way we know where things like `#include <plat.h>` are coming from.
=> libopenthread: namespace platform

examples/tests/ieee802154/radio_tx_raw/main.c
This PR updates the 15.4 `radio_tx_raw` app to send a more full fledged 15.4 broadcast packet including a 60 byte payload.
=> Update 15.4 radio_tx_raw app

libtock-sync/net/ieee802154.c
=> libtock-sync: 154: fix return error

libtock/services/alarm.c
https://github.com/tock/libtock-c/pull/395 has [stalled](https://github.com/tock/libtock-c/pull/395#issuecomment-2127624790) as the PR has grown beyond original scope. This PR splits out the modifications to arithmetic logic and should get merged before #395.
---
This mega-size comment was originally in the code explaining the logic of the code change.
```c
static uint32_t ms_to_ticks(uint32_t ms) {
uint32_t frequency;
libtock_alarm_command_get_frequency(&frequency);
// Note the following code is mathematically equivalent to the following
// more readable conversion.
// ```
//   uint32_t seconds         = ms / 1000;
//   uint32_t leftover_millis = ms % 1000;
//   uint32_t millihertz      = frequency / 1000; // ticks per millisecond
//   return (seconds * frequency) + (leftover_millis * …
=> alarm: create `ms_to_ticks` helper function

libtock/services/alarm.c
This is apparently not needed for newlib but is needed for picolib.
=> libtock: alarm: include assert.h

libtock-sync/net/ieee802154.c, libtock/net/ieee802154.c, libtock/net/ieee802154.h, libtock/net/syscalls/ieee802154_syscalls.c, libtock/net/syscalls/ieee802154_syscalls.h
This supports adding a raw 15.4 interface for userspace. The changes are:
- Add radio on/off commands. We now have full control of the radio so we can do these.
- Add trying to turn the radio on when checking if the radio is up. Before we could assume the kernel was managing the stack. To not have two divergent stacks in userspace, this speculatively tries to turn on the radio. On the kernel-managed stack this will fail, but we don't care. On the raw stack this may be necessary, otherwise the radio isn't on.
- Use 64-bit interfaces rather than sharing a cfg buffer to set/get 64 bit addresses.
=> 15.4: Add new raw 15.4 commands; try to turn on radio

shell.nix
With the 24.05 nixpkgs release, we should be good to add jlink back. I have added necessary deps uncrustify and unzip. Decompressing newlib fails (silently) and tries to reinstall every time if `unzip` is unavailable.
Built all examples successfully.
CC: @lschuermann
=> shell.nix: update deps, add jlink

libtock-sync/net/ieee802154.c
Prior to the tutorial, I altered the 15.4 transmit sync method to timeout after a provided delay in an attempt to fix a bug. This was unrelated and the original `yield_for` works correctly. This reverts the changes.
=> Revert libtock-sync IEEE802154 tx

examples/tutorials/hotp/hotp_milestone_one/Makefile, examples/tutorials/hotp/hotp_milestone_one/main.c, examples/tutorials/hotp/hotp_milestone_one/screen.c, examples/tutorials/hotp/hotp_milestone_one/screen.h, examples/tutorials/hotp/hotp_milestone_three/Makefile, examples/tutorials/hotp/hotp_milestone_three/main.c, examples/tutorials/hotp/hotp_milestone_three/screen.c, examples/tutorials/hotp/hotp_milestone_three/screen.h, examples/tutorials/hotp/hotp_milestone_two/Makefile, examples/tutorials/hotp/hotp_milestone_two/main.c, examples/tutorials/hotp/hotp_milestone_two/screen.c, examples/tutorials/hotp/hotp_milestone_two/screen.h
Since we have screens on our tutorial boards, this would use them for the HOTP tutorial examples.
I'm not exactly sure how (or if) to integrate this into the tutorial flow, however. Using the screen is not really the point (and completely optional).
=> HOTP Tutorial: Add screen support

examples/tests/alarm_in_overflow/Makefile, examples/tests/alarm_in_overflow/README.md, examples/tests/alarm_in_overflow/main.c, examples/tests/gpio/gpio_original/main.c, examples/tests/multi_alarm_test/main.c, libnrfserialization/serialization_tock.c, libopenthread/platform/alarm.c, libtock-sync/services/alarm.c, libtock-sync/services/alarm.h, libtock-sync/services/unit_test.c, libtock/services/alarm.c, libtock/services/alarm.h
PR fixes https://github.com/tock/tock/issues/3879
Tock does not support setting alarms more than 2^32 ticks in the future as the `alarm_at` syscall takes in ticks. For the default nrf52840 tock configuration at 32KHz, the greatest possible value for the syscall alarm is 37 hours.
`timer_in` takes in milliseconds, but is flawed in that it is just a wrapper around `alarm_at` which can only accept a max value of 2^32 ticks. Thus, calling `timer_in` longer than 2^32 ticks in milliseconds will not have the expected behavior. `delay_ms` calls `timer_in`, so it is flawed for the same reason.
We fixed this by modifying `timer_in`. If the timer length is longer than the time that `alarm_at` can count up to, then `timer_in` will schedule multiple alarms to reach the full length. We calculate the …
=> timer: handle timer overflow

examples/tutorials/thread_network/screen/temperature_sensor_app/Makefile
I'm guessing this was copied and should be removed.
=> tutorial: thread: no openthread for sensor app

shell.nix
#444 attempted to re-add segger-jlink only under the condition that `withUnfreePkgs` is true, but actually includes it implicitly in `LD_LIBRARY_PATH`.
This PR wraps the addition of that package in the same conditional.
Tested by entering the nix-shell with both `withUnfreePkgs` enabled and without.
=> Fix nix shell: withUnfreePackages = false

lib/fetch-libc++.sh, lib/fetch-newlib.sh
=> use default shasum for os x if present

examples/tests/nonvolatile_storage/main.c
Small fix to nonvolatile storage test. The call to `libtocksync_nonvolatile_storage_read` should populate `readbuf` instead of `writebuf` so that the test can verify the capsule reads the same data that was written.
=> fix nonvolatile storage test

shell.nix
Just adds openocd, which is required for flashing in lieu of JLinkExe on some boards, to the shell.nix expression.
=> Add openocd to shell.nix

Configuration.mk
This allows building Tock applications for VeeR EL2  (see related PR: https://github.com/tock/tock/pull/4118)
=> configuration: add target for VeeR EL2

examples/tests/multi_alarm_simple_overflow_test/Makefile, examples/tests/multi_alarm_simple_overflow_test/README.md, examples/tests/multi_alarm_simple_overflow_test/main.c, examples/tests/multi_alarm_simple_test/Makefile, examples/tests/multi_alarm_simple_test/README.md, examples/tests/multi_alarm_simple_test/main.c, libtock/services/alarm.c, libtock/services/alarm.h
This PR fixes a subtle bug in the userspace virtual alarm library. If alarms are created and expire pretty close to each other, the `within_range` check can incorrectly return the relative relationship between the two, place the earlier alarm _after_ the later alarm, which is incorrect, and can end up totally starving the earlier alarm if the later alarm is repeating.
This bug was introduced when trying to correctly account for potentially overflowing alarms, and the "obvious" fix (just compare absolute expiration values) doesn't work.
This PR adds two tests, one that demonstrates the starved alarm issue and one that exercises the overflow issue, and fixes the bug in such a way that both pass. In particular, the fix is simply to explicitly check if alarms overflow when insert them to the …
=> Fix multi-alarm overlapping bug

examples/lvgl/lvgl_driver.c, examples/lvgl/main.c, lvgl/Makefile, lvgl/lv_conf.h
This PR upgrades the LVGL library to version 9.2.0 and adjusts the example lvgl application accordingly.
This is mostly a straightforward port, though there is some cleanup of global variables etc to make the application example slightly more cannonical C using some of the better ergonomics of newer LVGL API.
Most significantly, this PR now elides the process-level conversion of the frame buffer from normal RGB565 to a swapped version for SPI and other busses that swap them (see: https://docs.lvgl.io/master/porting/display.html#swap-endianness). My argument is that including this at the process level is inappropriate and non-portable, instead individual drivers in the kernel should account for swapping bytes if needed.
This is currently not the case for at least the `st77xx` driver, but I …
=> Upgrade LVGL to v9.2.0

libnrfserialization/serialization_tock.c
This alarm was created with the `ms` interface and needs to be cancelled by it as well.
=> libnrfserialization: use correct alarm cancel api

examples/tests/alarms/alarm_in_overflow/main.c, libopenthread/platform/alarm.c, libtock/services/alarm.c, libtock/services/alarm.h
Use of timezone in `{get/set}timeofday` is deprecated.
If something did try to pass us the parameter, our implementation would (incorrectly) ignore it. More significantly, our implementation does not check that the `timeval` struct is nonnull before dereferencing it.
This updates libtock's interface to match our implementation and the common-case scenario, and leaves the question of what to do if something tries to use the legacy `tz` parameter to whomever implements the wrapper.
=> alarm: remove references to timezone

libtock/net/ieee802154.c
In the libtock sync/async rewrite, the CFG buffer length allowed to the kernel was mistakenly changed from 11 to 27. This reverts the mistake.
This resolves https://github.com/tock/tock/issues/4227.
=> 15.4: Fix CFG buffer length allowed to kernel (tx)

Configuration.mk, libc++/docker/docker-libc++-14.1.0/Dockerfile, libc++/docker/docker-libc++-14.1.0/docker-create.sh, newlib/Makefile, newlib/docker/docker-newlib-4.4.0.20231231/Dockerfile, newlib/docker/docker-newlib-4.4.0.20231231/docker-create.sh
#442 has an unfortunate chicken-and-egg problem wherein a commit new enough to checkout by hash in the dockerfile will only exist in the main libtock-c repo if the pull request comes from a branch within the libtock-c repo.
Hence this PR, which is based on the external branch, but is now coming from an internal branch. This isn't the most ergonomic or friendly solution, but this is also a rare enough issue [hopefully] that a little occasional human labor seems the path of least resistance.
I added commits to update the repo path, remove the unneeded patch file, and update the hash to check out.
---
~~TODO: Technically, the Makefile change to only patch if there's a patchfile is untested as newlib is still building on my laptop, but I doubt there will be any issue~~ Hubris will get you …
=>  Support the latest newlib, libc++ and GCC (replaces #442)

.gitmodules, RadioLib/Makefile.app, RadioLib/libtockHal.h, examples/build_all.sh, examples/lora/sensor-lorawan/.gitignore, examples/lora/sensor-lorawan/CayenneLPP.cc, examples/lora/sensor-lorawan/CayenneLPP.h, examples/lora/sensor-lorawan/LICENSE.GPL, examples/lora/sensor-lorawan/Makefile, examples/lora/sensor-lorawan/README.md, examples/lora/sensor-lorawan/main.cc, examples/lora/sensor-lorawan/radioConfig_example.h, examples/lora/sensor-receive/main.cc, examples/lora/sensor-transmit/main.cc
This builds on top of https://github.com/tock/libtock-c/pull/432 and adds a LoRaWAN example where a Tock system can send data to [TTN](https://www.thethingsnetwork.org/).
=> lora: Initial commit of LoRaWAN example

examples/sensors/main.c, libtock-sync/sensors/moisture.c, libtock-sync/sensors/moisture.h, libtock/sensors/moisture.c, libtock/sensors/moisture.h, libtock/sensors/syscalls/moisture_syscalls.c, libtock/sensors/syscalls/moisture_syscalls.h
Support the new moisture sensor and add a environment sensor example application
=> examples: sensors: Support moisture readings

libtock/net/syscalls/ieee802154_syscalls.c
During the libtock-sync rewrite, the set short address syscall command number was mistakenly copied. This PR fixes the mistake.
=> 15.4 Set Address Syscall Fix

libtock/net/ieee802154.c
The prior payload offset calculation did not account for the 3 metadata bytes each frame buffer contains when passed from the kernel. Buffers are of the form:
```
|     1 byte          |       1 byte            |      1 byte      |  HEADER | PAYLOAD  | MIC |
(Header len)         (Payload len)          (mic len)          
```
This PR updates the offset calculation.
=> [15.4] Fix payload offset calculation

examples/tutorials/thread_network/08_screen_u8g2/main.c, examples/tutorials/thread_network/09_screen_final/main.c, examples/tutorials/thread_network/10_screen_ipc/main.c
This cleans up the diff between the `sensor_final` and `sensor_ipc` to be just the changes relevant to ipc; since we point folks to the diff instead of implementing, seems worth cleaning up, but it's also not _critical_ per se, and I didn't want to merge code changes without more eyes
=> [net tutorial]: remove inconsequntial diff content

AppMakefile.mk, Helpers.mk
Adding even a trailing space causes the build to fail.
=> make: ensure PACKAGE_NAME has no spaces

examples/tutorials/thread_network/06_screen/Makefile, examples/tutorials/thread_network/07_screen_button/Makefile, examples/tutorials/thread_network/08_screen_u8g2/Makefile, examples/tutorials/thread_network/09_screen_final/Makefile, examples/tutorials/thread_network/09_screen_final/main.c, examples/tutorials/thread_network/10_screen_ipc/Makefile, examples/tutorials/thread_network/10_screen_ipc/main.c, examples/tutorials/thread_network/11_sensor_ipc/main.c
1. Remove trailing space in package name for screen apps.
2. Reset yield variable in 09_screen_final so the loop doesn't run continuously.
3. Return on failed IPC callback.
4. Allow screen app to work without openthread.
=> thread tutorial fixes

RadioLib/libtockHal.h
To avoid overflows casts the timer to 64-bits.
=> RadioLib: libtockHal.h: Cast time calculation to 64-bit

shell.nix
- **shell.nix: libusb renamed to libusb1**
- **shell.nix: cargoSha256 renamed to cargoHash**
- **shell.nix: update to Tockloader v0.13.0**
=> Misc shell.nix updates

shell.nix
The libtock-c formatting scripts expect to use a specific version of `uncrustify` (v0.75.1, currently), and will attempt to build it if not present. Instead of using whatever version the user's Nixpkgs has, we build the specific `uncrustify` version required by `libtock-c`.
=> shell.nix: add specific uncrustify version (0.75.1)

libtock/Makefile, libtock/util/README.md, libtock/util/streaming_process_slice.c, libtock/util/streaming_process_slice.h
This adds userspace helpers implementing the "streaming process slice" contract as implemented in the Tock kernel in [1]. Instead of working with two separate buffers, these helpers present an interface similar to a regular read-write allow based on a single buffer. Internally, this buffer is then subdivided into an "application-owned" and "kernel-owned" part which are swapped atomically. The caller is responsible for keeping a `streaming_process_slice_state_t`, and is provided with ephemeral references to the kernel-written payloads on each swap operation. The full, original buffer can be reclaimed by deinitializing the `streaming_process_slice_state_t` struct.
Currently, these helpers are quite minimal and do not expose the ability to set any optional flags (such as `halt`). They are …
=> libtock: add util/streaming_process_slice

Configuration.mk
This is related to #377, when running
```
TOCK_TARGETS="cortex-m4" ./build_all.sh
```
One ends up getting a lot of messages if they don't have the riscv compiler installed,
```console
make: riscv64-unknown-elf-gcc: No such file or directory
```
This appears to be because `Configuration.mk` runs the compiler to try and extract the compiler version.
This patch tries to only run the compiler/extract the version if the `TOCK_TARGETS` contains the string `rv32`.
I tested two cases:
* With `TOCK_TARGETS="cortex-m4"`, ensuring it doesn't produce the error
* Without `TOCK_TARGETS` set, ensuring it still does because the default value contains the string.
=> If not targeting an architecture family don't run it's compiler

tools/uncrustify/uncrustify.sh
At some point GNU grep decided to deprecate the `egrep` utility in favor of `grep -E`.
```text
$ /usr/bin/egrep 'whatever' /dev/null
egrep: warning: egrep is obsolescent; using grep -E
```
I haven't tested building on other platforms/operating systems, but given that posix grep does define
the `-E` argument to grep, but does not appear to require an egrep command it seems like
one should prefer it.
https://pubs.opengroup.org/onlinepubs/9799919799/utilities/grep.html#top
=> avoid `egrep` obsolecent warning by switching to `grep -E`.

Configuration.mk, examples/tests/crash_dummy/main.c, libtock-sync/display/text_screen.c
This is basically a no-op at this point, as C23 didn't really break anything*.
The prior selection of C11 was mostly arbitrary. At the time the first
libtock-c build infrastructure was built, C17 hadn't been ratified yet,
but we needed some newer stuff than C99 provided, so we explicitly set
things to C11 (well, gnu11).
We have an impending need for the new C23 `#embed` compiler directive,
so this version bump lays the groundwork.
Future PRs may also look at other new C23 features; there are many that
are likely useful to libtock-c.
*There was one function signature it's more persnickety about, which
is the other commit in this PR.
=> Update default compilation to C23 (from C11)

examples/build_all.sh, examples/format_all.sh
Now instead of the world's longest (and slowest to load) ci text output, we get:
(Where you can click to expand any of those groups to see their contents)
=> ci: group output of builds separately

lr1110/Makefile.setup, lr1110/lr1110/src_changed/lr11xx_hal.c, lr1110/lr1110/src_changed/smtc_hal_flash.c, lr1110/lr1110/src_changed/smtc_hal_gpio.c, lr1110/lr1110/src_changed/smtc_hal_mcu.c, lr1110/lr1110/src_changed/smtc_hal_rtc.c
After #502, the (newer than CI) compiler (on my machine) is a bit stricter / catches some things that result in hard errors.
These fixup the missing includes and other small warnings that were now promoted to errors.
The switch away from `unzip + mv + rmdir` is to (1) simplify, and (2) handle hidden directories correctly (since there is now a `.github/` folder in the upstream root).
=> Lr1110 quickfixes

lib/fetch-libc++.sh, lib/fetch-newlib.sh
What it says on the tin — if the hash verification fails, print some info about what was downloaded to help debug.
=> ci: add some prints to help debug errors

libopenthread/platform/flash.c, libopenthread/platform/radio.c
This PR updates the `libopenthread` platform to now use the isolated nv storage capsule. 
Additionally, in testing/debugging the isolated nv issues, I discovered that the current radio platform implementation does not call `config_commit` after changing the radio (resulting in the radio not being updated). This is now fixed.
=> OpenThread Updates/Fixes

shell.nix
It seems like something has changed in the way that Nix or Cargo
calculates the hash over the locked Cargo dependencies, which causes
builds to break on Nixpkgs >= 25.05.
For the time being, let's do a version check and support both Nixpkgs
>= 25.05pre and < 25.05pre with different `cargoHash`es.
=> shell.nix: use different cargoHash for Nixpkgs >= 25.05pre

.github/workflows/ci.yml, examples/tests/kv/kv_system/main.c, libnrfserialization/Makefile
The removes the version pin from the arm gcc toolchain used in CI. We don't pin the RISC-V version, and I don't think we should pin ARM either (just use 'latest' implicitly instead). If new compilers have issues, it'd be nice to catch them in CI proactively. Warnings also get measurably better with each version, and I doubt we intended to have a compiler in CI that's 5 years out of date...
This PR also removes the toolchain install from the `ci-format` job, since the toolchains aren't used there anyway.
=> CI: Don't pin ARM GCC version

libtock-sync/Makefile, libtock-sync/crypto/hmac.c, libtock-sync/crypto/hmac.h, libtock-sync/crypto/syscalls/hmac_syscalls.c, libtock-sync/crypto/syscalls/hmac_syscalls.h, libtock/crypto/hmac.c, libtock/crypto/hmac.h, libtock/crypto/hmac_types.h, libtock/defer.h
This is a minimal example of what "cleanup attribute" like code would look like.
This probably isn't the exact best way to implement it (due to the "magic variable name" of `ret_{param}`), but it gives a sense of what it would look like.
=> Yield-WaitFor: Introduce `defer` and update HMAC as example usage

doc/guide.md, examples/lvgl/lvgl_driver.c, examples/tests/touch/main.c, examples/tests/udp/udp_rx/main.c, examples/tests/udp/udp_virt_rx_tests/app1/main.c, examples/tests/udp/udp_virt_rx_tests/app2/main.c, libopenthread/platform/radio.c, libtock-sync/net/ieee802154.c, libtock-sync/net/udp.c, libtock/crypto/hmac.c, libtock/crypto/sha.c, libtock/interface/console.c, libtock/net/ieee802154.c, libtock/net/ieee802154.h, libtock/net/udp.c, libtock/net/udp.h, libtock/peripherals/crc.c, libtock/peripherals/rtc.c, libtock/sensors/moisture.c, libtock/sensors/rainfall.c, libtock/sensors/touch.c, libtock/sensors/touch.h, libtock/storage/isolated_nonvolatile_storage.c, libtock/storage/kv.c, libtock/tock.c, libtock/tock.h
StatusCode only exists over the syscall interface. Once we are in libtock-c we only use ReturnCode.
We need to make sure we use tock_status_to_returncode() on values passed over the syscall interface.
=> Improve how we use returncode_t vs statuscode_t.

Configuration.mk
We need to move the memory to start at 0x80300000. This also enables up to four apps. I don't know what the best way to assign addresses is, but this tries to space them differently to enable apps of different sizes.
=> make: support up to four qemu_rv32 apps

Configuration.mk
Since libtock-sync now requires Yield-WaitFor, apps will need to use at least the 2.2 kernel.
=> make: required kernel version 2.2

AppMakefile.mk
PR #525 doesn't seem to work, it doesn't actually trigger a build of the library. Not sure why that passed CI...
This fixes the rules so that there is actually a build recipe for the library now. Should fix the `u8g2` issue for #542; testing locally on a fresh checkout `u8g2` didn't build on that branch or on master, but does build now.
=> make: fix sentinel rules

doc/guide.md
- Add unallow example in libtock-sync
- Add note about _types.h file
=> doc: guide: update with more style changes
