README.md
This is also an attempt to test out bors, so let's see what happens.
=> add badges to top-level README

examples/tests/analog_comparator/Makefile, examples/tests/analog_comparator/README.md, examples/tests/analog_comparator/main.c, libtock/analog_comparator.c, libtock/analog_comparator.h
Test application for the analog comparator which was merged in the main repository a few days ago.
=> Added test application for the analog comparator

examples/services/ble-env-sense/test-with-sensors/Makefile, examples/services/ble-env-sense/test-with-sensors/README.md, examples/services/ble-env-sense/test-with-sensors/main.c
This is a test app for the BLE ESS service app.
=> Add app to use BLE ESS service with real sensors

examples/tests/console_recv_long/Makefile, examples/tests/console_recv_long/README.md, examples/tests/console_recv_long/main.c, examples/tests/console_recv_short/Makefile, examples/tests/console_recv_short/README.md, examples/tests/console_recv_short/main.c
Two basic test apps.
Note these do not seem to work when run concurrently.
=> add two uart recv apps

examples/tests/ambient_light/Makefile, examples/tests/ambient_light/README.md, examples/tests/ambient_light/main.c
Add a simple test for the ambient light syscall.
=> test: add ambient_light test

examples/tests/gpio_interrupt/Makefile, examples/tests/gpio_interrupt/README.md, examples/tests/gpio_interrupt/main.c
Prints a message on a GPIO interrupt.
Useful for testing GPIO virtualization.
=> add gpio interrupt test app

examples/tests/button_print/Makefile, examples/tests/button_print/README.md, examples/tests/button_print/main.c
Test for virtualization of buttons.
=> add button test app

libtock/ambient_light.h, libtock/humidity.h, libtock/temperature.h
Per tock/tock#655 units for temperature, humidity and ambient_light are added to the header files.
=> Specify units in header files

libtock/crt0.c, libtock/tock.c, newlib/Makefile, newlib/build-riscv.sh
Updates crt0.c and tock.c to support RISC-V.
Also adds newlib support for riscv.
=> Add RISC-V Support

libtock/gpio.h
=> Fix stale comment for GPIO_Pin_t in libtock/gpio.h

Program.mk
This updates the flashing commands in Program.mk since Tockloader has been updated.
Fixes #54
=> program.mk: update as tockloader has changed

examples/tests/adc_single_samples/Makefile, examples/tests/adc_single_samples/README.md, examples/tests/adc_single_samples/main.c
=> add adc single test app

examples/tests/callback_remove_test01/Makefile, examples/tests/callback_remove_test01/README.md, examples/tests/callback_remove_test01/main.c
Verify that unsubscribed callbacks are in fact removed.
=> add callback_remove_test

examples/tests/gpio_loopback_test/Makefile, examples/tests/gpio_loopback_test/README.md, examples/tests/gpio_loopback_test/main.c, libtock/gpio.c, libtock/gpio.h
Test for https://github.com/tock/tock/pull/1406
=> Add gpio loopback test.

libnrfserialization/serialization_tock.c, libtock/nrf51_serialization.c, libtock/nrf51_serialization.h
This changes the nRF serialization library to call reset when it first starts.
I've tested this with restarting the hail app on hail.
=> nrf51 serialization: call reset to start

userland_generic.ld
=> Update dead link in documentation

examples/l3gd20/Makefile, examples/l3gd20/main.c, examples/sensors/main.c, libtock/l3gd20.c, libtock/l3gd20.h, libtock/ninedof.c, libtock/ninedof.h
Added the user space for the l3gd20 capsule (https://github.com/tock/tock/pull/1723).
Updated the ninedof user space and added the gyroscope functions.
=> User space library for L3gd20 driver

AppMakefile.mk
=> AppMakefile.mk: Fix the linker ordering

.gitignore, .vscode/settings.json, examples/lsm303dlhc/Makefile, examples/lsm303dlhc/main.c, examples/sensors/main.c, libtock/lsm303dlhc.c, libtock/lsm303dlhc.h
This adds the lsm303dlhc user space for https://github.com/tock/tock/pull/1754.
The lsm303dlhc api may be used to fine tune the sensor, getting data may be used thorught the ninedof.
=> Lsm303dlhc userspace

examples/tests/mpu_flash_end/Makefile, examples/tests/mpu_flash_end/README.md, examples/tests/mpu_flash_end/main.c, examples/tests/mpu_ram_end/Makefile, examples/tests/mpu_ram_end/README.md, examples/tests/mpu_ram_end/main.c
These are useful for testing specific MPU features.
=> Add simple new MPU tests

examples/sensors/main.c
Actually read the ninedof sensors.
=> sensors app: actually read ninedof

libtock/crt0.c
May not always be the same as the stack pointer.
=> crt0: set r9 correctly for cortex-m

Configuration.mk
Remove keyword `override` so the variables are changeable with make
arguments.
Fixes #114
=> Allow toolchains to bet set

libtock/ambient_light.c, libtock/console.c, libtock/spi.c
Updates libtock-c ambient_light to use 2.0 API.
=> Updating ambient light to 2.0 API.

examples/lvgl/lvgl_driver.c, examples/lvgl/main.c, examples/screen/main.c, libtock/screen.c
The pull request updates the screen API to the 2.0 syscall and fixes and lvgl driver issue.
=> Tock 2.0: update screen to use the 2.0 API

examples/tests/i2c/i2c_master_slave_ping_pong/main.c, examples/unit_tests/nrf52840dk-test/main.c, libtock/button.c, libtock/button.h
Port `button.h` and `button.c` to the new driver trait a la tock/tock#2331
=> Tock 2.0 button driver

examples/touch/Makefile, examples/touch/main.c, libtock/touch.c, libtock/touch.h
This pull request adds the touch driver API and example.
It should close #126
=> Tock 2.0: touch api and example app for 2.0 API

examples/sensors/main.c, libtock/sound_pressure.c, libtock/sound_pressure.h
This PR adds the user space API for the sound pressure driver (https://github.com/tock/tock/pull/2364) and adds the sound pressure driver to the example sensors app.
=> Tock 2.0: sound pressure API

libtock/ninedof.c
The PR updates the ninedof driver API.
=> Tock 2.0: ninedof driver API

examples/tests/gpio/README.md, examples/tests/gpio/main.c, libtock/gpio.c
Also updates the test API. Tested.
=> Update GPIO to Tock 2.0 syscalls.

examples/tests/i2c/i2c_master_ping_pong/Makefile, examples/tests/i2c/i2c_master_ping_pong/README.md, examples/tests/i2c/i2c_master_ping_pong/main.c, libtock/i2c_master.c, libtock/i2c_master.h
This adds userspace support for I2C Master in libtock-c and adds a test application that works with the I2C Master/Slave test application.
=> I2C master library and test app.

libtock/sdcard.c
This has not been tested as no boards have an SDCard.
=> Update SDCard module to use Tock 2.0 system calls.

libtock/l3gd20.c
Port the l3gd20 capsule to tock 2.0
=> Port L3gd20 to Tock 2.0

examples/lvgl/Makefile
Fixes #197.
----
Tested via fresh checkout + build
=> Ensure lvgl submodule is present in example

libtock/crt0.c
=> remove volatile vars from crt0

examples/tests/crash_immediately_syscall/Makefile, examples/tests/crash_immediately_syscall/README.md, examples/tests/crash_immediately_syscall/main.c
This is a very small test app for testing what happens if an app crashes on its first instruction.
=> Add crash immediate with syscall test app

examples/tests/bare_bones/Makefile, examples/tests/bare_bones/README.md, examples/tests/bare_bones/main.c
This example shows how to make the smallest app:
- It requests no memory.
- It does not use crt0.c.
- It just immediately calls yield.
=> Add bare bones example app

libtock/spi.c, libtock/spi.h
=> libtock/spi: Split out subscribe and allow commands

examples/tests/sha/main.c
=> examples/tests/sha: Ensure we set the SHA algorthirm

examples/sensors/main.c
This:
- Prints the sensors which will be sampled.
- Updates the ambient light variable name.
- Fixes the print check for the temperature and humidity sensors.
=> sensors app: display available sensors

libtock/text_screen.c
=> supress uninit buffer warning

examples/tests/hifive1b/Makefile, examples/tests/hifive1b/README.md, examples/tests/hifive1b/main.c
Sets these variables:
```
STACK_SIZE=512
KERNEL_HEAP_SIZE=512
APP_HEAP_SIZE=0
```
=> add hifive1b test app with proper mem sizes

examples/tests/malloc_test02/Makefile, examples/tests/malloc_test02/README.md, examples/tests/malloc_test02/main.c
Add a simple test app that checks that a large malloc fails correctly.
Running this currently causes a fault.
=> add malloc_test02

libtock/sdcard.c
Tested on hardware to confirm.
SD card testing app in `examples/tests/sdcard/` works successfully with these updates.
=> SD Card bugfixes for Tock 2.0

libtock/button.c, libtock/button.h
Renamed the parameters of the button library to button_* instead of pin_* .
=> renamed button parameters

Configuration.mk
=> Configuration.mk: Add support for ESP32-C3

examples/lvgl/Makefile, examples/lvgl/lvgl_driver.c, examples/lvgl/lvgl_driver.h, examples/lvgl/main.c, examples/touch/Makefile, examples/touch/main.c, libtock/screen.c, libtock/touch.c, libtock/touch.h, lvgl/Makefile, lvgl/README.md, lvgl/lv_conf.h
This pull request:
- update screen driver the new allow usage
- update touch driver
- add touch example
- update lvgl to version 8
- update lvgl example
This was tested using Tock 2.0
=> Update UI libraries

examples/tests/kv_system/Makefile, examples/tests/kv_system/README.md, examples/tests/kv_system/main.c, libtock/kv_system.c, libtock/kv_system.h
This uses https://github.com/tock/tock/pull/2928 and access and tests Tock's KV System
=> Add userspace support for the Key/Value System

libtock/screen.c
The PR fixes the screen API to use the new screen driver that uses synchronous system call for getting the resolution and pixel mode.
=> Fixes the screen API to use the improved driver

README.md
=> readme: add slack link

examples/ble-uart/ble_nus.c, examples/ble_advertising/main.c, examples/rot13_service/main.c, examples/sensors/main.c, examples/tests/rf233/rf233.c, examples/tests/sdcard/main.c, examples/witenergy/main.c, libtock/buzzer.c, libtock/ieee802154.c, tools/uncrustify/uncrustify.sh
This doesn't look to have any effect on our formatting, but might
hopefully fix M1 mac issues?
@alexandruradovici Does the newest version run on M1 mac?
(uncrustify is also available in homebrew, and the script will pick up your local copy if it's available).
=> bump uncrustify version

examples/tests/microbit_v2/Makefile, examples/tests/microbit_v2/README.md, examples/tests/microbit_v2/main.c
This app tests the supported libtock-c libraries on the Microbit. It has limited usefulness without using tockloader listen, but some tests use the LED matrix to display results.
=> created a Micro:bit v2 test app, similar to the Hail test app

shell.nix
This is required for `_FORTIFY_SOURCE` to work. In the default configuration, the newlib libc shipped with the compiler and used for header includes during compilation does not have SSP enabled. Thus use the flag `--enable-libssp` to enable SSP support.
However, GCC also by default builds its own libc, which needs to be disabled. Further, during compilation of GCC, the
`gcc_cv_libc_provides_ssp` environment variable must be set, as otherwise the newlib SSP support conflicts with GCC's SSP support (itself requiring glibc).
While this does work, it compiles GCC when entering libtock-c's nix-shell for the first time. This seems to be a worthwhile tradeoff, considering that this makes the libtock-c build infrastructure work without further adjustments.
=> shell.nix: use riscv32-none-elf toolchain w/ newlib & ssp enabled

examples/music/main.c, examples/tests/microbit_v2/main.c
More specifically, I raised the notes in music up two octaves so that each note played is at least 489 hz, and raised the notes in the Microbit test app by one octave for the same reason. Also, I added a comment in the Microbit test app mentioning that the Microbit can't play frequencies below 489 hz.
=> changed notes to ones that the Microbit can play and removed *3

examples/tests/keyboard_hid/Makefile, examples/tests/keyboard_hid/README.md, examples/tests/keyboard_hid/main.c, libtock/usb_keyboard_hid.c, libtock/usb_keyboard_hid.h
Libtock and example app to use USB keyboard with Tock.
Tested after the kernel side was merged.
=> Add support for USB HID keyboard

Configuration.mk
This should allow us to compile 0 stack apps again.
=> make: update elf2tab to 0.12.0

libtock/ambient_light.c, libtock/ambient_light.h, libtock/humidity.c, libtock/humidity.h, libtock/pressure.c, libtock/pressure.h, libtock/sound_pressure.c, libtock/sound_pressure.h, libtock/temperature.c, libtock/temperature.h
Helpful for writing a generic sensor app, such as in a tutorial.
=> Add exists() checks for sensors

shell.nix
=> Update elf2tab in nix shell

examples/tests/u8g2-demos/graph/Makefile, examples/tests/u8g2-demos/graph/README.md, examples/tests/u8g2-demos/graph/graph.c, examples/tests/u8g2-demos/graph/graph.h, examples/tests/u8g2-demos/graph/main.c
This adds a demo app that graphs data using the u8g2 library.
=> U8g2 graph app

examples/tutorials/hotp/hotp_milestone_two/main.c, examples/tutorials/hotp/hotp_oracle_complete/main.c
=> HOTP: Remove app state from milestone 2

examples/tests/u8g2-demos/led-menu/Makefile, examples/tests/u8g2-demos/led-menu/README.md, examples/tests/u8g2-demos/led-menu/main.c, u8g2/Makefile, u8g2/u8g2-tock.c
This also adds a simple test app where the interface can control LEDs.
=> u8g2: add support for menus

examples/tests/screen-tock/Makefile, examples/tests/screen-tock/README.md, examples/tests/screen-tock/main.c
Writes TOCK in blocks on the screen.
=> Add screen-tock test app

libtock/tock.c, libtock/tock.h
This PR adds support to parse the returncode and `u64` value in a `u64` command returntype.
=> u64 returncode 

examples/tutorials/hotp/hotp_milestone_one/main.c, examples/tutorials/hotp/hotp_milestone_one/step0.c, examples/tutorials/hotp/hotp_milestone_one/step0.h, examples/tutorials/hotp/hotp_milestone_three/Makefile, examples/tutorials/hotp/hotp_milestone_three/main.c, examples/tutorials/hotp/hotp_milestone_two/Makefile, examples/tutorials/hotp/hotp_milestone_two/main.c, examples/tutorials/hotp/hotp_milestone_two/step1.c, examples/tutorials/hotp/hotp_oracle_complete/main.c, examples/tutorials/hotp/hotp_starter/main.c
Several updates needed after testing all of the apps.
=> hotp: fix to new libtock and kv

libtock-sync/net/ieee802154.c
This updates the libtock-sync send raw to timeout after 100ms. This prevents a failing or delayed 15.4 transmission from blocking the application. This PR also adds separate objects for maintaining state across raw/standard sending.
This fixes a last minute bug found in the Thread tutorial, but I am not convinced this is necessarily the correct approach long term.
=> IEEE802154 libtock-sync sending timeout

AppMakefile.mk, TockLibrary.mk
That way if the config changes, uncrustify will run again.
=> make: depend on uncrustify config

libopenthread/platform/radio.c, libopenthread/platform/system.c
This builds on the other 15.4 PRs, but adds more platform support to openthread.
=> openthread: update with new 15.4 calls

libtock-sync/kernel/read_only_state.c, libtock/tock.c, libtock/tock.h
This PR removes code and API related to task queue which isn't in use anymore.
=> Clean up unused task queue code

examples/tutorials/thread_tutorials/encrypted_sensor_data/02_openthread_final/main.c, examples/tutorials/thread_tutorials/encrypted_sensor_data/03_encrypted_data_final/main.c
This PR makes a few small fixes to the checkpoint files and printing the encrypted data to avoid weird behavior in the console.
=>  Encrypted Sensor Data Tutorial - Minor Updates

examples/tests/hmac/README.md, examples/tests/hmac/main.c
Verified against https://cryptii.com/pipes/hmac.
=> tests: hmac: add check for correctness
